### ISSUE TITLE
To-hit rolls not working - Bug

### ISSUE THREAD

**Issue by Rhodes62** [Vendare/DarkHeresy2E-FoundryVTT#92]
Getting an issue after the recent update. When I try to use the Combat button on any sheet to roll for anything with a Clip size of anything other than 0/0 on any weapon it comes out with this error on the console:

![Bug](https://user-images.githubusercontent.com/120424621/207289332-980c7b9a-d7c1-4a68-8e17-3a1a146c1356.PNG)

Uncaught (in promise) Error: Roll.safeEval produced a non-numeric result from expression ""
[Detected 1 package: system:dark-heresy]
    at Roll.safeEval (foundry.js:9387:13)
    at Roll._evaluateTotal (foundry.js:9303:36)
    at Roll._evaluateSync (foundry.js:9290:24)
    at Roll.evaluate (foundry.js:9211:64)
    at _computeDamage (roll.js:126:13)
    at _rollDamage (roll.js:96:26)
    at async combatRoll (roll.js:17:12)
    at async Object.callback (dialog.js:100:21)

**Comment by Vendare** [comment]
Created a Hotfix. Ranged Weapons should now work again correctly

**Comment by Rhodes62** [comment]
@Vendare
<img width="324" alt="Error" src="https://user-images.githubusercontent.com/120424621/207497125-0e25d66b-a2c3-40b0-8a0e-54714495c60d.PNG">

Still not working even after the manifest update fix.
